spring.application.name=SpringBoot_Hibernate_JoinORM

#Config Datasource
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/ecom_db
spring.datasource.username=root
spring.datasource.password=sondz1

hibernate.show_sql = true
hibernate.ddl-auto = update
hibernate.dialect = org.hibernate.dialect.MySQLDialect
hibernate.format_sql = true